POST http://localhost:8000/users
Content-Type: application/json

{
  "email" : "mzoughi-hedi@hotmail.comuuuu",
  "password" : "1234",
  "role" : "doctor",
  "first_name" : "Hedi",
  "inami" : "4445",
  "name" : "Mzoughi",
  "phone_number" : "0483659044"
}

###

POST http://localhost:8000/login
Content-type: application/json

{
  "email": "mzoughi-hedi@hotmail.com",
  "password": "1234"
}

###
